[versions]
# Gradle
check-style = "10.26.0"
shadow = "9.1.0"
resource-factory = "1.3.0"
run-paper = "3.0.2"
gremlin = "0.0.9"
indra-licenser-spotless = "3.2.0"

# Java
paper-api = "1.21.10-R0.1-SNAPSHOT"
mini-placeholders = "3.0.1"
configurate = "4.2.0"
adventure-serializer-configurate = "4.24.0"
kotonoha = "0.1.0-SNAPSHOT"

[libraries]
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-api" }
mini-placeholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "mini-placeholders" }
configurate-yaml = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate" }
adventure-serializer-configurate = { group = "net.kyori", name = "adventure-serializer-configurate4", version.ref = "adventure-serializer-configurate" }
kotonoha-message = { group = "io.github.namiuni", name = "kotonoha-message", version.ref = "kotonoha"}
kotonoha-message-extra-miniplaceholders = { group = "io.github.namiuni", name = "kotonoha-message-extra-miniplaceholders", version.ref = "kotonoha"}
kotonoha-translator = { group = "io.github.namiuni", name = "kotonoha-translator", version.ref = "kotonoha"}

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
resource-factory = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "resource-factory" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
gremlin = { id = "xyz.jpenilla.gremlin-gradle", version.ref = "gremlin" }
indra-licenser-spotless = { id = "net.kyori.indra.licenser.spotless", version.ref = "indra-licenser-spotless" }